apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2021-07-08T06:42:30Z"
  labels:
    app: n1
  name: n1
  namespace: default
  resourceVersion: "382631"
  uid: 568bfd0d-5cd2-42f2-baad-c4fc9f998464
spec:
  clusterIP: 10.233.18.95
  clusterIPs:
  - 10.233.18.95
  externalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 32053
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: n1
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
